# Generated by Django 3.1.7 on 2021-03-23 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ERRV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Name')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Latitude')),
                ('prob', models.FloatField(verbose_name='Probability')),
                ('type_solution', models.FloatField(default='201', verbose_name='Solution')),
            ],
        ),
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Name')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Latitude')),
                ('r_time', models.FloatField(verbose_name='Require_Time')),
                ('c_flaf', models.FloatField(default='101', verbose_name='Flag c')),
                ('number_of_people', models.IntegerField(verbose_name='People')),
                ('prob_accident', models.FloatField(verbose_name='Probability_ac')),
            ],
        ),
    ]
