# Generated by Django 3.1.7 on 2021-03-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errv',
            name='prob',
            field=models.FloatField(default='0', verbose_name='Probability'),
        ),
    ]
